### ISSUE TITLE
Error: env.lookup(...).filter is not a function

### ISSUE THREAD

**Issue by ABVN-Chuong** [SAP-samples/ui5-typescript-tutorial#17]
Hello everyone,

I'm trying to create new project using ts-app but when I installed with **yo easy-ui5 ts-app** , I got the error **env.lookup(...).filter is not a function** like pic below. I used node version 21.2.0 and easy-ui5 version 3.6.3

So, I can't know how to fix that. If you know how to fix, please share me. Thank you so much!
![image](https://github.com/SAP-samples/ui5-typescript-tutorial/assets/140793877/670e449f-9fb4-4145-ba9f-91967b618aca)

**Comment by akudev** [comment]
@ABVN-Chuong: I can confirm this issue when using node 21. The issue is in easy-ui5, though and has been fixed earlier today: https://github.com/SAP/generator-easy-ui5/issues/137

Please either update to easy-ui5 3.7.0 or use node 20 or 18.
